### ISSUE TITLE
Displayed window numbering starts at 2

### ISSUE THREAD

**Issue by heikkil** [luismbo/wn-mode#2]
My displayed window numbers start at 2 and the actual numbers start at 1. In my example below, the mode line shows #3, but I can move the point there with M-2.

I do not know if my emacs setup somehow messes up the window order, but here is some debug info:

The effect is persistent over emacs reboots. Current frame setup: Left side has one window "emacs.org". Right side has two windows: *scratch* on top, *Messages* at bottom.

````
(selected-window)
=> #<window 6 on *scratch*>

(wn--window-list)
=> (#<window 4 on  *Minibuf-0*> #<window 3 on emacs.org> #<window 6 on *scratch*> #<window 8 on *Messages*>)

(reverse (wn--window-list))
=> (#<window 8 on *Messages*> #<window 6 on *scratch*> #<window 3 on emacs.org> #<window 4 on  *Minibuf-0*>)

(memq (selected-window) (reverse (wn--window-list)))
=> (#<window 6 on *scratch*> #<window 3 on emacs.org> #<window 4 on  *Minibuf-0*>)

(length (memq (selected-window) (reverse (wn--window-list))))
=> 3 (#o3, #x3, ?\C-c)
````
M-0 tells me "Minibuffer is inactive."

The modified function below that takes one from the computed value fixes the problem for me:

````
(defun wn--selected-window-number ()
  "Return the number of the selected window"
  ;; this strange implementation avoids a dependency on cl-position!
  (1- (length (memq (selected-window) (reverse (wn--window-list))))))
````

**Comment by luismbo** [comment]
Doh. Thanks! :-)
